### ISSUE TITLE
Stress output using SILO

### ISSUE THREAD

**Issue by kinanbezem7** [ORNL/CabanaPD#161]
I'm running the crack_branching example on the VirialStress branch, but don't see the stress output on paraview when trying to view the .silo output files. I'm trying now to get HDF5 working with wsl on a windows machine.

**Comment by kinanbezem7** [comment]
Update: stress is output is supported in HDF5

**Comment by kinanbezem7** [comment]
> It's unclear whether this a paraview issue in reading Silo matrices or a Cabana issue in implementing the Silo output for matrices. Either way, I'm closing this as not a CabanaPD issue - can you open a separate one for the HDF5 errors you're seeing?

There may have been a misunderstanding, I believe the issue was getting HDF5 working on windows, I don't believe it was an issue with CabanaPD itself. I managed to get it working on wsl though.

**Comment by streeve** [comment]
> > It's unclear whether this a paraview issue in reading Silo matrices or a Cabana issue in implementing the Silo output for matrices. Either way, I'm closing this as not a CabanaPD issue - can you open a separate one for the HDF5 errors you're seeing?
> 
> There may have been a misunderstanding, I believe the issue was getting HDF5 working on windows, I don't believe it was an issue with CabanaPD itself. I managed to get it working on wsl though.

Oh right I did forget that it was only windows. Happy to take a look if you add the details, but glad hdf5 is working
