### ISSUE TITLE
Error:  Cabana must be compiled with SILO

### ISSUE THREAD

**Issue by diehlpk** [ORNL/CabanaPD#20]
Hi,

I followed the instructions

spack install cabana+cajita 

and I get some error while configuring CabanaPD:

 cmake ..
-- Enabled Kokkos devices: SERIAL
CMake Error at CMakeLists.txt:25 (message):
  Cabana must be compiled with SILO
Call Stack (most recent call first):
  CMakeLists.txt:31 (CabanaPD_check_enabled)

-- Configuring incomplete, errors occurred!
See also "/work/diehlpk/Compile/medusa/cabanapd/CabanaPD/build/CMakeFiles/CMakeOutput.log".

How do I compile Cabana with Silo?

**Comment by streeve** [comment]
Unfortunately we're currently missing a Silo spack build for Cabana. I'll add that, but until that's available you would need a Cabana build from source (https://github.com/ECP-copa/Cabana/wiki/CPU-Build) which includes Silo (https://github.com/ECP-copa/Cabana/wiki/Optional-Build#silo). Note that we're also planning to transition to direct HDF5 support in #15

I'll update this issue with the spack PR

**Comment by streeve** [comment]
spack/spack/pull/37393

**Comment by streeve** [comment]
With the spack develop branch you can now use `spack install cabana+cajita+silo`. Let me know if you have any issues

**Comment by diehlpk** [comment]
Thanks, I am trying it right now.

**Comment by diehlpk** [comment]
it worked, will build CabanaPD soon.

**Comment by streeve** [comment]
> it worked, will build CabanaPD soon.

Great! Feel free to reopen as needed
