### ISSUE TITLE
MPI is not found

### ISSUE THREAD

**Issue by diehlpk** [ORNL/CabanaPD#26]
I followed the instructions to compile CabanaPD, however, it seems MPI is not found

```
[ 50%] Linking CXX executable ElasticWave
/usr/bin/ld: cannot find -lMPI::MPI_C
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/ElasticWave.dir/build.make:104: examples/ElasticWave] Error 1
make[1]: *** [CMakeFiles/Makefile2:171: examples/CMakeFiles/ElasticWave.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
What did I miss?

**Comment by streeve** [comment]
Hmm I haven't seen this before - it's only missing the C bindings (which it doesn't need). Does the machine you're building on have HDF5 installed?

**Comment by diehlpk** [comment]
The machine has a module for hdf5, but spack should not be aware of the module.

**Comment by streeve** [comment]
I wasn't able to reproduce with a `spack`-installed Cabana, but if you post more details I can keep looking into this

**Comment by diehlpk** [comment]
I am at a conference this week and will post more next week.

**Comment by diehlpk** [comment]
@streeve I fixed the compilation error and will do some pull request soon.

I had a similar issues with some other project.
